#!/usr/bin/env python

from __future__ import (
    absolute_import,
    division,
    print_function,
    unicode_literals,
)

import argparse
import collections
import datetime
import json
import logging as _logging
import os.path
import plistlib
import re
import subprocess
import sys

logger = _logging.getLogger("macsigcheck")


class SignatureDB(collections.MutableMapping):
    def __init__(self, db_path, tilde_for_home_dir=None):
        self._db_path = db_path
        if os.path.exists(db_path):
            logger.debug("Opening DB at %r", db_path)
            with open(db_path, "r") as db_file:
                self._db = json.load(
                    db_file, object_pairs_hook=collections.OrderedDict
                )
        else:
            logger.debug("New database")
            self._db = {}
        if tilde_for_home_dir:
            self._home_dir = os.path.normpath(os.path.expanduser("~"))
            self._home_dir_regexp = re.compile(
                r"^%s(/|$)" % (re.escape(self._home_dir),)
            )
        else:
            self._home_dir = self._home_dir_regexp = None

    def __getitem__(self, path):
        return self._db[path]

    def __setitem__(self, path, value):
        self._db[path] = value

    def __delitem__(self, path):
        del self._db[path]

    def __iter__(self):
        return iter(self._db)

    def __len__(self):
        return len(self._db)

    def write(self):
        logger.debug("Writing to %r", self._db_path)
        with open(self._db_path, "w") as db_file:
            json.dump(
                self._db,
                db_file,
                sort_keys=True,
                indent=4,
                separators=(",", ": "),
            )

    def process_paths(self, path):
        """Returns (expanded_path, db_path) for the given path.

        expanded_path has tilde expansion performed on it.  db_path is
        the path that should be used as the key into this database.

        """
        norm_path = os.path.normpath(path)
        expanded_path = os.path.expanduser(norm_path)
        possible_keys = [path, norm_path, expanded_path]
        if self._home_dir_regexp and self._home_dir_regexp.search(norm_path):
            tilded_path = "~%s" % (norm_path[len(self._home_dir) :],)
            possible_keys.append(tilded_path)
        else:
            tilded_path = norm_path
        for key in possible_keys:
            if key in self._db:
                logger.debug("%s: Found existing path %r in DB", path, key)
                return expanded_path, key
        else:
            logger.debug("%s: No existing entry in DB", path)
            return expanded_path, tilded_path


def check_signature(path, assessment_type=None, stdout_plist=None):
    if not assessment_type:
        if re.search(r".*/Library/PreferencePanes/[^/]+.prefPane$", path, re.I):
            assessment_type = "open"
        else:
            assessment_type = "execute"
    cmd = [
        "spctl",
        "-a",
        "-t",
        assessment_type,
        # I think this is only necessary for testing DMG
        # files, but it seems harmless for the other
        # purposes as well.
        "--context",
        "context:primary-signature",
        "--raw",
        "-vv",
        "--ignore-cache",
        path,
    ]
    logger.debug("running %r", cmd)
    spctl = subprocess.Popen(
        cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE
    )
    stdout, stderr = spctl.communicate()
    if spctl.returncode == 0 and stdout_plist:
        stdout = plistlib.readPlistFromString(stdout)
    return spctl.returncode, stdout, stderr


def main(argv):
    parser = argparse.ArgumentParser(prog=argv[0])
    parser.add_argument(
        "--db", "-D", default=os.path.expanduser("~/.macsigcheck.json")
    )
    parser.add_argument(
        "--no-substitute-tilde",
        dest="tilde_for_home_dir",
        default=True,
        action="store_false",
    )
    parser.add_argument(
        "--add",
        "-a",
        action="store_true",
        help="""\
            Add new targets to the DB.  Does not check existing
            targets.""",
    )
    parser.add_argument(
        "--freshen",
        "-F",
        action="store_true",
        help="""\
            Update signature information for targets already in the DB.""",
    )
    parser.add_argument(
        "--update",
        "-u",
        action="store_true",
        help="""\
            Add or update signatures in the DB.  This is --add and
            --freshen together.""",
    )
    parser.add_argument("--verbose", "-v", default=False, action="store_true")
    parser.add_argument("--debug", "-d", default=False, action="store_true")
    parser.add_argument("targets", nargs="*")
    args = parser.parse_args(argv[1:])
    if args.debug:
        logger.setLevel(_logging.DEBUG)
    elif args.verbose:
        logger.setLevel(_logging.INFO)
    if args.add and not args.targets:
        raise Exception("Used --add but didn't provide targets to add")
    if args.update:
        if args.add or args.freshen:
            logger.warning("--update implies both --add and --freshen")
        args.add = args.freshen = True
    db = SignatureDB(args.db, tilde_for_home_dir=args.tilde_for_home_dir)
    now = str(datetime.datetime.now())
    failed = False
    changed = False
    for target in args.targets or db.iterkeys():
        logger.debug("%s: Processing", target)
        expanded_target, target = db.process_paths(target)
        if not os.path.exists(expanded_target):
            if args.targets:
                raise Exception("%r does not exist" % (target,))
            else:
                logger.info("%s: Does not exist, skipping", target)
                continue
        is_new = target not in db
        assert not is_new or args.targets
        if is_new and not args.add:
            logger.error(
                "%s: Not in DB, cannot check signature (did you forget --add?)",
                target,
            )
            failed = True
            continue
        if is_new:
            db_entry = {}
        else:
            db_entry = db[target]
        will_write = is_new or args.freshen
        spctl_status, spctl_result, spctl_stderr = check_signature(
            expanded_target, db_entry.get("assessment_type"), stdout_plist=True
        )
        if spctl_status != 0:
            logger.error(
                "%s: Cannot verify signature (%r): %s",
                target,
                spctl_status,
                spctl_stderr.strip(),
            )
            failed = True
        else:
            try:
                originator = spctl_result["assessment:originator"]
            except KeyError:
                raise Exception(
                    "%s: Cannot get originator from spctl" % (target,)
                )
            expected_originator = db_entry.get("originator")
            if expected_originator:
                if expected_originator.startswith("id:"):
                    expected_originator = r"\(%s\)$" % (
                        re.escape(expected_originator[3:]),
                    )
                originator_changed = not re.search(
                    expected_originator, originator
                )
            else:
                originator_changed = False
            if will_write:
                if expected_originator and originator_changed:
                    logger.warn(
                        "%s: Originator changing from %r to %r",
                        target,
                        db_entry["originator"],
                        originator,
                    )
                if not expected_originator or originator_changed:
                    match = re.search(r"\(([A-Z0-9]+)\)$", originator)
                    if match:
                        expected_originator = "id:%s" % (match.group(1),)
                    else:
                        expected_originator = "^%s$" % (re.escape(originator),)
                    db_entry["originator"] = expected_originator
                    logger.info(
                        "%s: %s with originator %r",
                        target,
                        "Created" if is_new else "Updated",
                        originator,
                    )
                else:
                    logger.info("%s: No change", target)
                db_entry["last_updated"] = now
                changed = True
                if is_new:
                    logger.debug("%s: Adding to DB", target)
                    db[target] = db_entry
            elif originator_changed:
                logger.error(
                    "%s: Originator changed from %r to %r",
                    target,
                    expected_originator,
                    originator,
                )
                failed = True
            else:
                logger.info(
                    "%s: Verified%s",
                    target,
                    ", including originator" if expected_originator else "",
                )
    if changed:
        db.write()
    return 1 if failed else 0


if __name__ == "__main__":
    _logging.basicConfig()
    sys.exit(main(sys.argv))
